
export const CURRENTUSERPROFILE = 'CURRENTUSERPROFILE';
// export const ISUSERLOGIN = 'ISUSERLOGIN';
export const LOADER = 'LOADER';
export const ISERROR = 'ISERROR';
export const CONTACTS = 'CONTACTS';
export const TOTALCONTACTS = 'TOTALCONTACTS';
export const OTPSUPPORTED = 'OTPSUPPORTED';
export const INITIALROUTE = 'INITIALROUTE';
export const SPLASHSTATUSBAR = 'SPLASHSTATUSBAR';
export const SCREENLOADER = 'SCREENLOADER';
export const SEARCHEDDATA = 'SEARCHEDDATA';
export const CONTACTTYPESCOUNT = 'CONTACTTYPESCOUNT';
export const SPECIALITIES = 'SPECIALITIES';
export const PAGINATIONLOADER = 'PAGINATIONLOADER';
export const GET_INDUSTRIES_SUCCESS = 'GET_INDUSTRIES_SUCCESS';
export const GET_JOB_TYPES_SUCCESS = 'GET_JOB_TYPES_SUCCESS';
export const IS_BUSINESS_USER = 'GET_BUSINESS_USER_STATUS';
