
export const CURRENTUSERPROFILE = 'CURRENTUSERPROFILE';
// export const ISUSERLOGIN = 'ISUSERLOGIN';
export const LOADER = 'LOADER';
export const ISERROR = 'ISERROR';
export const CONTACTS = 'CONTACTS';
export const OTPSUPPORTED = 'OTPSUPPORTED';
export const INITIALROUTE = 'INITIALROUTE';
export const SPLASHSTATUSBAR = 'SPLASHSTATUSBAR';
export const SCREENLOADER = 'SCREENLOADER';
export const SEARCHEDDATA = 'SEARCHEDDATA';