
export const CONTACTTYPEDATA = ["Client", 'Pro', 'Supplier', 'Staff'];
export const EMAILLABELDATA = ["Home", 'Work', 'Other',];
export const CONTACTTYPECOLORDATA = ["#FBC02D", '#26A69A', '#EF5350', '#5C6BC0'];
export const WEBSITEDATA = ["Homepage"];
export const SECTIONLISTDATA: any = [
  { value: ':)', key: 'lCUTs2_1' },
  { value: 'Allen', key: 'lCUTs2_2' },
  { value: 'Lillie-Mai Allen', key: 'lCUTs2_3' },
  { value: 'Emmanuel Goldstein', key: 'TXdL0c_1' },
  { value: 'Winston Smith', key: 'zqsiEw_1' },
  { value: 'William Blazkowicz', key: 'psg2PM_1' },
  { value: 'Gordon Comstock', key: '1K6I18_1' },
  { value: 'Philip Ravelston', key: 'NVHSkA_1' },
  { value: 'Rosemary Waterlow', key: 'SaHqyG_1' },
  { value: 'Julia Comstock', key: 'iaT1Ex_1' },
  { value: 'Mihai Maldonado', key: 'OvMd5e_1' },
  { value: 'Murtaza Molina', key: '25zqAO_1' },
  { value: 'Peter Petigrew', key: '8cWuu3_1' },
  { value: ':)', key: 'lCUTs2_4' },
  { value: 'Allen', key: 'lCUTs2_5' },
  { value: 'Lillie-Mai Allen', key: 'lCUTs2_6' },
  { value: 'Emmanuel Goldstein', key: 'TXdL0c_2' },
  { value: 'Winston Smith', key: 'zqsiEw_2' },
  { value: 'William Blazkowicz', key: 'psg2PM_2' },
  { value: 'Gordon Comstock', key: '1K6I18_2' },
  { value: 'Philip Ravelston', key: 'NVHSkA_2' },
  { value: 'Rosemary Waterlow', key: 'SaHqyG_2' },
  { value: 'Julia Comstock', key: 'iaT1Ex_2' },
  { value: 'Mihai Maldonado', key: 'OvMd5e_2' },
  { value: 'Murtaza Molina', key: '25zqAO_2' },
  { value: 'Peter Petigrew', key: '8cWuu3_2' },
  { value: ':)', key: 'lCUTs2_7' },
  { value: 'Allen', key: 'lCUTs2_8' },
  { value: 'Lillie-Mai Allen', key: 'lCUTs2_9' },
  { value: 'Emmanuel Goldstein', key: 'TXdL0c_3' },
  { value: 'Winston Smith', key: 'zqsiEw_3' },
  { value: 'William Blazkowicz', key: 'psg2PM_3' },
  { value: 'Gordon Comstock', key: '1K6I18_3' },
  { value: 'Philip Ravelston', key: 'NVHSkA_3' },
  { value: 'Rosemary Waterlow', key: 'SaHqyG_3' },
  { value: 'Julia Comstock', key: 'iaT1Ex_3' },
  { value: 'Mihai Maldonado', key: 'OvMd5e_3' },
  { value: 'Murtaza Molina', key: '25zqAO_3' },
  { value: 'Peter Petigrew', key: '8cWuu3_3' },
];
