
export const CONTACTTYPEDATA = ["Client", 'Pro', 'Supplier', 'Staff'];
export const CONTACTTYPECOLORDATA = ["#FBC02D", '#26A69A', '#EF5350', '#5C6BC0'];
export const SECTIONLISTDATA= [
    { value: ':)', key: 'lCUTs2' },
    { value: 'Allen', key: 'lCUTs2' },
    { value: 'Lillie-Mai Allen', key: 'lCUTs2' },
    { value: 'Emmanuel Goldstein', key: 'TXdL0c' },
    { value: 'Winston Smith', key: 'zqsiEw' },
    { value: 'William Blazkowicz', key: 'psg2PM' },
    { value: 'Gordon Comstock', key: '1K6I18' },
    { value: 'Philip Ravelston', key: 'NVHSkA' },
    { value: 'Rosemary Waterlow', key: 'SaHqyG' },
    { value: 'Julia Comstock', key: 'iaT1Ex' },
    { value: 'Mihai Maldonado', key: 'OvMd5e' },
    { value: 'Murtaza Molina', key: '25zqAO' },
    { value: 'Peter Petigrew', key: '8cWuu3' },
    { value: ':)', key: 'lCUTs2' },
    { value: 'Allen', key: 'lCUTs2' },
    { value: 'Lillie-Mai Allen', key: 'lCUTs2' },
    { value: 'Emmanuel Goldstein', key: 'TXdL0c' },
    { value: 'Winston Smith', key: 'zqsiEw' },
    { value: 'William Blazkowicz', key: 'psg2PM' },
    { value: 'Gordon Comstock', key: '1K6I18' },
    { value: 'Philip Ravelston', key: 'NVHSkA' },
    { value: 'Rosemary Waterlow', key: 'SaHqyG' },
    { value: 'Julia Comstock', key: 'iaT1Ex' },
    { value: 'Mihai Maldonado', key: 'OvMd5e' },
    { value: 'Murtaza Molina', key: '25zqAO' },
    { value: 'Peter Petigrew', key: '8cWuu3' },
    { value: ':)', key: 'lCUTs2' },
    { value: 'Allen', key: 'lCUTs2' },
    { value: 'Lillie-Mai Allen', key: 'lCUTs2' },
    { value: 'Emmanuel Goldstein', key: 'TXdL0c' },
    { value: 'Winston Smith', key: 'zqsiEw' },
    { value: 'William Blazkowicz', key: 'psg2PM' },
    { value: 'Gordon Comstock', key: '1K6I18' },
    { value: 'Philip Ravelston', key: 'NVHSkA' },
    { value: 'Rosemary Waterlow', key: 'SaHqyG' },
    { value: 'Julia Comstock', key: 'iaT1Ex' },
    { value: 'Mihai Maldonado', key: 'OvMd5e' },
    { value: 'Murtaza Molina', key: '25zqAO' },
    { value: 'Peter Petigrew', key: '8cWuu3' },
    { value: ':)', key: 'lCUTs2' },
    { value: 'Allen', key: 'lCUTs2' },
    { value: 'Lillie-Mai Allen', key: 'lCUTs2' },
    { value: 'Emmanuel Goldstein', key: 'TXdL0c' },
    { value: 'Winston Smith', key: 'zqsiEw' },
    { value: 'William Blazkowicz', key: 'psg2PM' },
    { value: 'Gordon Comstock', key: '1K6I18' },
    { value: 'Philip Ravelston', key: 'NVHSkA' },
    { value: 'Rosemary Waterlow', key: 'SaHqyG' },
    { value: 'Julia Comstock', key: 'iaT1Ex' },
    { value: 'Mihai Maldonado', key: 'OvMd5e' },
    { value: 'Murtaza Molina', key: '25zqAO' },
    { value: 'Peter Petigrew', key: '8cWuu3' },
  ]
  