import { CountryCodeModal, SpecialitiesModal } from "../../core/modals/contact.modal";

export const COUNTRY_LIST: CountryCodeModal[] = [
    {
        "name": "Afghanistan",
        "code": "af",
        "flag": 0,
        "phoneCode": "\u002B93",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 1
    },
    {
        "name": "Albania",
        "code": "al",
        "flag": 0,
        "phoneCode": "\u002B355",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 2
    },
    {
        "name": "Algeria",
        "code": "dz",
        "flag": 0,
        "phoneCode": "\u002B213",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 3
    },
    {
        "name": "American Samoa",
        "code": "as",
        "flag": 0,
        "phoneCode": "\u002B1",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 4
    },
    {
        "name": "Andorra",
        "code": "ad",
        "flag": 0,
        "phoneCode": "\u002B376",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 5
    },
    {
        "name": "Angola",
        "code": "ao",
        "flag": 0,
        "phoneCode": "\u002B244",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 6
    },
    {
        "name": "Anguilla",
        "code": "ai",
        "flag": 0,
        "phoneCode": "\u002B1",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 7
    },
    {
        "name": "Antigua \u0026 Barbuda",
        "code": "ag",
        "flag": 0,
        "phoneCode": "\u002B1",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 8
    },
    {
        "name": "Argentina",
        "code": "ar",
        "flag": 0,
        "phoneCode": "\u002B54",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 9
    },
    {
        "name": "Armenia",
        "code": "am",
        "flag": 0,
        "phoneCode": "\u002B374",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 10
    },
    {
        "name": "Aruba",
        "code": "aw",
        "flag": 0,
        "phoneCode": "\u002B297",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 11
    },
    {
        "name": "Ascension Island",
        "code": "ac",
        "flag": 0,
        "phoneCode": "\u002B247",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 12
    },
    {
        "name": "Australia",
        "code": "au",
        "flag": 0,
        "phoneCode": "\u002B61",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 13
    },
    {
        "name": "Austria",
        "code": "at",
        "flag": 0,
        "phoneCode": "\u002B43",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 14
    },
    {
        "name": "Azerbaijan",
        "code": "az",
        "flag": 0,
        "phoneCode": "\u002B994",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 15
    },
    {
        "name": "Bahamas",
        "code": "bs",
        "flag": 0,
        "phoneCode": "\u002B1",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 16
    },
    {
        "name": "Bahrain",
        "code": "bh",
        "flag": 0,
        "phoneCode": "\u002B973",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 17
    },
    {
        "name": "Bangladesh",
        "code": "bd",
        "flag": 0,
        "phoneCode": "\u002B880",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 18
    },
    {
        "name": "Barbados",
        "code": "bb",
        "flag": 0,
        "phoneCode": "\u002B1",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 19
    },
    {
        "name": "Belarus",
        "code": "by",
        "flag": 0,
        "phoneCode": "\u002B375",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 20
    },
    {
        "name": "Belgium",
        "code": "be",
        "flag": 0,
        "phoneCode": "\u002B32",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 21
    },
    {
        "name": "Belize",
        "code": "bz",
        "flag": 0,
        "phoneCode": "\u002B501",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 22
    },
    {
        "name": "Benin",
        "code": "bj",
        "flag": 0,
        "phoneCode": "\u002B229",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 23
    },
    {
        "name": "Bermuda",
        "code": "bm",
        "flag": 0,
        "phoneCode": "\u002B1",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 24
    },
    {
        "name": "Bhutan",
        "code": "bt",
        "flag": 0,
        "phoneCode": "\u002B975",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 25
    },
    {
        "name": "Bolivia",
        "code": "bo",
        "flag": 0,
        "phoneCode": "\u002B591",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 26
    },
    {
        "name": "Bosnia \u0026 Herzegovina",
        "code": "ba",
        "flag": 0,
        "phoneCode": "\u002B387",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 27
    },
    {
        "name": "Botswana",
        "code": "bw",
        "flag": 0,
        "phoneCode": "\u002B267",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 28
    },
    {
        "name": "Brazil",
        "code": "br",
        "flag": 0,
        "phoneCode": "\u002B55",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 29
    },
    {
        "name": "British Indian Ocean Territory",
        "code": "io",
        "flag": 0,
        "phoneCode": "\u002B246",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 30
    },
    {
        "name": "British Virgin Islands",
        "code": "vg",
        "flag": 0,
        "phoneCode": "\u002B1",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 31
    },
    {
        "name": "Brunei",
        "code": "bn",
        "flag": 0,
        "phoneCode": "\u002B673",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 32
    },
    {
        "name": "Bulgaria",
        "code": "bg",
        "flag": 0,
        "phoneCode": "\u002B359",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 33
    },
    {
        "name": "Burkina Faso",
        "code": "bf",
        "flag": 0,
        "phoneCode": "\u002B226",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 34
    },
    {
        "name": "Burundi",
        "code": "bi",
        "flag": 0,
        "phoneCode": "\u002B257",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 35
    },
    {
        "name": "Cambodia",
        "code": "kh",
        "flag": 0,
        "phoneCode": "\u002B855",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 36
    },
    {
        "name": "Cameroon",
        "code": "cm",
        "flag": 0,
        "phoneCode": "\u002B237",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 37
    },
    {
        "name": "Canada",
        "code": "ca",
        "flag": 0,
        "phoneCode": "\u002B1",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 38
    },
    {
        "name": "Cape Verde",
        "code": "cv",
        "flag": 0,
        "phoneCode": "\u002B238",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 39
    },
    {
        "name": "Caribbean Netherlands",
        "code": "bq",
        "flag": 0,
        "phoneCode": "\u002B599",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 40
    },
    {
        "name": "Cayman Islands",
        "code": "ky",
        "flag": 0,
        "phoneCode": "\u002B1",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 41
    },
    {
        "name": "Central African Republic",
        "code": "cf",
        "flag": 0,
        "phoneCode": "\u002B236",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 42
    },
    {
        "name": "Chad",
        "code": "td",
        "flag": 0,
        "phoneCode": "\u002B235",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 43
    },
    {
        "name": "Chile",
        "code": "cl",
        "flag": 0,
        "phoneCode": "\u002B56",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 44
    },
    {
        "name": "China",
        "code": "cn",
        "flag": 0,
        "phoneCode": "\u002B86",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 45
    },
    {
        "name": "Colombia",
        "code": "co",
        "flag": 0,
        "phoneCode": "\u002B57",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 46
    },
    {
        "name": "Comoros",
        "code": "km",
        "flag": 0,
        "phoneCode": "\u002B269",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 47
    },
    {
        "name": "Congo - Brazzaville",
        "code": "cg",
        "flag": 0,
        "phoneCode": "\u002B242",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 48
    },
    {
        "name": "Congo - Kinshasa",
        "code": "cd",
        "flag": 0,
        "phoneCode": "\u002B243",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 49
    },
    {
        "name": "Cook Islands",
        "code": "ck",
        "flag": 0,
        "phoneCode": "\u002B682",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 50
    },
    {
        "name": "Costa Rica",
        "code": "cr",
        "flag": 0,
        "phoneCode": "\u002B506",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 51
    },
    {
        "name": "C\u00F4te d\u0060Ivoire",
        "code": "ci",
        "flag": 0,
        "phoneCode": "\u002B225",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 52
    },
    {
        "name": "Croatia",
        "code": "hr",
        "flag": 0,
        "phoneCode": "\u002B385",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 53
    },
    {
        "name": "Cuba",
        "code": "cu",
        "flag": 0,
        "phoneCode": "\u002B53",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 54
    },
    {
        "name": "Cura\u00E7ao",
        "code": "cw",
        "flag": 0,
        "phoneCode": "\u002B599",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 55
    },
    {
        "name": "Cyprus",
        "code": "cy",
        "flag": 0,
        "phoneCode": "\u002B357",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 56
    },
    {
        "name": "Czechia",
        "code": "cz",
        "flag": 0,
        "phoneCode": "\u002B420",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 57
    },
    {
        "name": "Denmark",
        "code": "dk",
        "flag": 0,
        "phoneCode": "\u002B45",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 58
    },
    {
        "name": "Djibouti",
        "code": "dj",
        "flag": 0,
        "phoneCode": "\u002B253",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 59
    },
    {
        "name": "Dominica",
        "code": "dm",
        "flag": 0,
        "phoneCode": "\u002B1",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 60
    },
    {
        "name": "Dominican Republic",
        "code": "do",
        "flag": 0,
        "phoneCode": "\u002B1",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 61
    },
    {
        "name": "Ecuador",
        "code": "ec",
        "flag": 0,
        "phoneCode": "\u002B593",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 62
    },
    {
        "name": "Egypt",
        "code": "eg",
        "flag": 0,
        "phoneCode": "\u002B20",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 63
    },
    {
        "name": "El Salvador",
        "code": "sv",
        "flag": 0,
        "phoneCode": "\u002B503",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 64
    },
    {
        "name": "Equatorial Guinea",
        "code": "gq",
        "flag": 0,
        "phoneCode": "\u002B240",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 65
    },
    {
        "name": "Eritrea",
        "code": "er",
        "flag": 0,
        "phoneCode": "\u002B291",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 66
    },
    {
        "name": "Estonia",
        "code": "ee",
        "flag": 0,
        "phoneCode": "\u002B372",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 67
    },
    {
        "name": "Eswatini",
        "code": "sz",
        "flag": 0,
        "phoneCode": "\u002B268",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 68
    },
    {
        "name": "Ethiopia",
        "code": "et",
        "flag": 0,
        "phoneCode": "\u002B251",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 69
    },
    {
        "name": "Falkland Islands (Islas Malvinas)",
        "code": "fk",
        "flag": 0,
        "phoneCode": "\u002B500",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 70
    },
    {
        "name": "Faroe Islands",
        "code": "fo",
        "flag": 0,
        "phoneCode": "\u002B298",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 71
    },
    {
        "name": "Fiji",
        "code": "fj",
        "flag": 0,
        "phoneCode": "\u002B679",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 72
    },
    {
        "name": "Finland",
        "code": "fi",
        "flag": 0,
        "phoneCode": "\u002B358",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 73
    },
    {
        "name": "France",
        "code": "fr",
        "flag": 0,
        "phoneCode": "\u002B33",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 74
    },
    {
        "name": "French Guiana",
        "code": "gf",
        "flag": 0,
        "phoneCode": "\u002B594",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 75
    },
    {
        "name": "French Polynesia",
        "code": "pf",
        "flag": 0,
        "phoneCode": "\u002B689",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 76
    },
    {
        "name": "Gabon",
        "code": "ga",
        "flag": 0,
        "phoneCode": "\u002B241",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 77
    },
    {
        "name": "Gambia",
        "code": "gm",
        "flag": 0,
        "phoneCode": "\u002B220",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 78
    },
    {
        "name": "Georgia",
        "code": "ge",
        "flag": 0,
        "phoneCode": "\u002B995",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 79
    },
    {
        "name": "Germany",
        "code": "de",
        "flag": 0,
        "phoneCode": "\u002B49",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 80
    },
    {
        "name": "Ghana",
        "code": "gh",
        "flag": 0,
        "phoneCode": "\u002B233",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 81
    },
    {
        "name": "Gibraltar",
        "code": "gi",
        "flag": 0,
        "phoneCode": "\u002B350",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 82
    },
    {
        "name": "Greece",
        "code": "gr",
        "flag": 0,
        "phoneCode": "\u002B30",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 83
    },
    {
        "name": "Greenland",
        "code": "gl",
        "flag": 0,
        "phoneCode": "\u002B299",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 84
    },
    {
        "name": "Grenada",
        "code": "gd",
        "flag": 0,
        "phoneCode": "\u002B1",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 85
    },
    {
        "name": "Guadeloupe",
        "code": "gp",
        "flag": 0,
        "phoneCode": "\u002B590",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 86
    },
    {
        "name": "Guam",
        "code": "gu",
        "flag": 0,
        "phoneCode": "\u002B1",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 87
    },
    {
        "name": "Guatemala",
        "code": "gt",
        "flag": 0,
        "phoneCode": "\u002B502",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 88
    },
    {
        "name": "Guinea",
        "code": "gn",
        "flag": 0,
        "phoneCode": "\u002B224",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 89
    },
    {
        "name": "Guinea-Bissau",
        "code": "gw",
        "flag": 0,
        "phoneCode": "\u002B245",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 90
    },
    {
        "name": "Guyana",
        "code": "gy",
        "flag": 0,
        "phoneCode": "\u002B592",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 91
    },
    {
        "name": "Haiti",
        "code": "ht",
        "flag": 0,
        "phoneCode": "\u002B509",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 92
    },
    {
        "name": "Honduras",
        "code": "hn",
        "flag": 0,
        "phoneCode": "\u002B504",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 93
    },
    {
        "name": "Hong Kong",
        "code": "hk",
        "flag": 0,
        "phoneCode": "\u002B852",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 94
    },
    {
        "name": "Hungary",
        "code": "hu",
        "flag": 0,
        "phoneCode": "\u002B36",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 95
    },
    {
        "name": "Iceland",
        "code": "is",
        "flag": 0,
        "phoneCode": "\u002B354",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 96
    },
    {
        "name": "India",
        "code": "in",
        "flag": 0,
        "phoneCode": "\u002B91",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 97
    },
    {
        "name": "Indonesia",
        "code": "id",
        "flag": 0,
        "phoneCode": "\u002B62",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 98
    },
    {
        "name": "Iran",
        "code": "ir",
        "flag": 0,
        "phoneCode": "\u002B98",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 99
    },
    {
        "name": "Iraq",
        "code": "iq",
        "flag": 0,
        "phoneCode": "\u002B964",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 100
    },
    {
        "name": "Ireland",
        "code": "ie",
        "flag": 0,
        "phoneCode": "\u002B353",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 101
    },
    {
        "name": "Israel",
        "code": "il",
        "flag": 0,
        "phoneCode": "\u002B972",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 102
    },
    {
        "name": "Italy",
        "code": "it",
        "flag": 0,
        "phoneCode": "\u002B39",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 103
    },
    {
        "name": "Jamaica",
        "code": "jm",
        "flag": 0,
        "phoneCode": "\u002B1",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 104
    },
    {
        "name": "Japan",
        "code": "jp",
        "flag": 0,
        "phoneCode": "\u002B81",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 105
    },
    {
        "name": "Jordan",
        "code": "jo",
        "flag": 0,
        "phoneCode": "\u002B962",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 106
    },
    {
        "name": "Kazakhstan",
        "code": "kz",
        "flag": 0,
        "phoneCode": "\u002B7",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 107
    },
    {
        "name": "Kenya",
        "code": "ke",
        "flag": 0,
        "phoneCode": "\u002B254",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 108
    },
    {
        "name": "Kiribati",
        "code": "ki",
        "flag": 0,
        "phoneCode": "\u002B686",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 109
    },
    {
        "name": "Kosovo",
        "code": "xk",
        "flag": 0,
        "phoneCode": "\u002B383",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 110
    },
    {
        "name": "Kuwait",
        "code": "kw",
        "flag": 0,
        "phoneCode": "\u002B965",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 111
    },
    {
        "name": "Kyrgyzstan",
        "code": "kg",
        "flag": 0,
        "phoneCode": "\u002B996",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 112
    },
    {
        "name": "Laos",
        "code": "la",
        "flag": 0,
        "phoneCode": "\u002B856",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 113
    },
    {
        "name": "Latvia",
        "code": "lv",
        "flag": 0,
        "phoneCode": "\u002B371",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 114
    },
    {
        "name": "Lebanon",
        "code": "lb",
        "flag": 0,
        "phoneCode": "\u002B961",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 115
    },
    {
        "name": "Lesotho",
        "code": "ls",
        "flag": 0,
        "phoneCode": "\u002B266",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 116
    },
    {
        "name": "Liberia",
        "code": "lr",
        "flag": 0,
        "phoneCode": "\u002B231",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 117
    },
    {
        "name": "Libya",
        "code": "ly",
        "flag": 0,
        "phoneCode": "\u002B218",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 118
    },
    {
        "name": "Liechtenstein",
        "code": "li",
        "flag": 0,
        "phoneCode": "\u002B423",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 119
    },
    {
        "name": "Lithuania",
        "code": "lt",
        "flag": 0,
        "phoneCode": "\u002B370",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 120
    },
    {
        "name": "Luxembourg",
        "code": "lu",
        "flag": 0,
        "phoneCode": "\u002B352",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 121
    },
    {
        "name": "Macao",
        "code": "mo",
        "flag": 0,
        "phoneCode": "\u002B853",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 122
    },
    {
        "name": "Madagascar",
        "code": "mg",
        "flag": 0,
        "phoneCode": "\u002B261",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 123
    },
    {
        "name": "Malawi",
        "code": "mw",
        "flag": 0,
        "phoneCode": "\u002B265",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 124
    },
    {
        "name": "Malaysia",
        "code": "my",
        "flag": 0,
        "phoneCode": "\u002B60",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 125
    },
    {
        "name": "Maldives",
        "code": "mv",
        "flag": 0,
        "phoneCode": "\u002B960",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 126
    },
    {
        "name": "Mali",
        "code": "ml",
        "flag": 0,
        "phoneCode": "\u002B223",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 127
    },
    {
        "name": "Malta",
        "code": "mt",
        "flag": 0,
        "phoneCode": "\u002B356",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 128
    },
    {
        "name": "Marshall Islands",
        "code": "mh",
        "flag": 0,
        "phoneCode": "\u002B692",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 129
    },
    {
        "name": "Martinique",
        "code": "mq",
        "flag": 0,
        "phoneCode": "\u002B596",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 130
    },
    {
        "name": "Mauritania",
        "code": "mr",
        "flag": 0,
        "phoneCode": "\u002B222",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 131
    },
    {
        "name": "Mauritius",
        "code": "mu",
        "flag": 0,
        "phoneCode": "\u002B230",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 132
    },
    {
        "name": "Mexico",
        "code": "mx",
        "flag": 0,
        "phoneCode": "\u002B52",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 133
    },
    {
        "name": "Micronesia",
        "code": "fm",
        "flag": 0,
        "phoneCode": "\u002B691",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 134
    },
    {
        "name": "Moldova",
        "code": "md",
        "flag": 0,
        "phoneCode": "\u002B373",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 135
    },
    {
        "name": "Monaco",
        "code": "mc",
        "flag": 0,
        "phoneCode": "\u002B377",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 136
    },
    {
        "name": "Mongolia",
        "code": "mn",
        "flag": 0,
        "phoneCode": "\u002B976",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 137
    },
    {
        "name": "Montenegro",
        "code": "me",
        "flag": 0,
        "phoneCode": "\u002B382",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 138
    },
    {
        "name": "Montserrat",
        "code": "ms",
        "flag": 0,
        "phoneCode": "\u002B1",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 139
    },
    {
        "name": "Morocco",
        "code": "ma",
        "flag": 0,
        "phoneCode": "\u002B212",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 140
    },
    {
        "name": "Mozambique",
        "code": "mz",
        "flag": 0,
        "phoneCode": "\u002B258",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 141
    },
    {
        "name": "Myanmar (Burma)",
        "code": "mm",
        "flag": 0,
        "phoneCode": "\u002B95",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 142
    },
    {
        "name": "Namibia",
        "code": "na",
        "flag": 0,
        "phoneCode": "\u002B264",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 143
    },
    {
        "name": "Nauru",
        "code": "nr",
        "flag": 0,
        "phoneCode": "\u002B674",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 144
    },
    {
        "name": "Nepal",
        "code": "np",
        "flag": 0,
        "phoneCode": "\u002B977",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 145
    },
    {
        "name": "Netherlands",
        "code": "nl",
        "flag": 0,
        "phoneCode": "\u002B31",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 146
    },
    {
        "name": "New Caledonia",
        "code": "nc",
        "flag": 0,
        "phoneCode": "\u002B687",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 147
    },
    {
        "name": "New Zealand",
        "code": "nz",
        "flag": 0,
        "phoneCode": "\u002B64",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 148
    },
    {
        "name": "Nicaragua",
        "code": "ni",
        "flag": 0,
        "phoneCode": "\u002B505",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 149
    },
    {
        "name": "Niger",
        "code": "ne",
        "flag": 0,
        "phoneCode": "\u002B227",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 150
    },
    {
        "name": "Nigeria",
        "code": "ng",
        "flag": 0,
        "phoneCode": "\u002B234",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 151
    },
    {
        "name": "Niue",
        "code": "nu",
        "flag": 0,
        "phoneCode": "\u002B683",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 152
    },
    {
        "name": "Norfolk Island",
        "code": "nf",
        "flag": 0,
        "phoneCode": "\u002B672",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 153
    },
    {
        "name": "North Korea",
        "code": "kp",
        "flag": 0,
        "phoneCode": "\u002B850",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 154
    },
    {
        "name": "North Macedonia",
        "code": "mk",
        "flag": 0,
        "phoneCode": "\u002B389",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 155
    },
    {
        "name": "Northern Mariana Islands",
        "code": "mp",
        "flag": 0,
        "phoneCode": "\u002B1",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 156
    },
    {
        "name": "Norway",
        "code": "no",
        "flag": 0,
        "phoneCode": "\u002B47",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 157
    },
    {
        "name": "Oman",
        "code": "om",
        "flag": 0,
        "phoneCode": "\u002B968",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 158
    },
    {
        "name": "Pakistan",
        "code": "pk",
        "flag": 0,
        "phoneCode": "\u002B92",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 159
    },
    {
        "name": "Palau",
        "code": "pw",
        "flag": 0,
        "phoneCode": "\u002B680",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 160
    },
    {
        "name": "Palestine",
        "code": "ps",
        "flag": 0,
        "phoneCode": "\u002B970",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 161
    },
    {
        "name": "Panama",
        "code": "pa",
        "flag": 0,
        "phoneCode": "\u002B507",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 162
    },
    {
        "name": "Papua New Guinea",
        "code": "pg",
        "flag": 0,
        "phoneCode": "\u002B675",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 163
    },
    {
        "name": "Paraguay",
        "code": "py",
        "flag": 0,
        "phoneCode": "\u002B595",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 164
    },
    {
        "name": "Peru",
        "code": "pe",
        "flag": 0,
        "phoneCode": "\u002B51",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 165
    },
    {
        "name": "Philippines",
        "code": "ph",
        "flag": 0,
        "phoneCode": "\u002B63",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 166
    },
    {
        "name": "Poland",
        "code": "pl",
        "flag": 0,
        "phoneCode": "\u002B48",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 167
    },
    {
        "name": "Portugal",
        "code": "pt",
        "flag": 0,
        "phoneCode": "\u002B351",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 168
    },
    {
        "name": "Puerto Rico",
        "code": "pr",
        "flag": 0,
        "phoneCode": "\u002B1",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 169
    },
    {
        "name": "Qatar",
        "code": "qa",
        "flag": 0,
        "phoneCode": "\u002B974",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 170
    },
    {
        "name": "R\u00E9union",
        "code": "re",
        "flag": 0,
        "phoneCode": "\u002B262",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 171
    },
    {
        "name": "Romania",
        "code": "ro",
        "flag": 0,
        "phoneCode": "\u002B40",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 172
    },
    {
        "name": "Russia",
        "code": "ru",
        "flag": 0,
        "phoneCode": "\u002B7",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 173
    },
    {
        "name": "Rwanda",
        "code": "rw",
        "flag": 0,
        "phoneCode": "\u002B250",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 174
    },
    {
        "name": "Samoa",
        "code": "ws",
        "flag": 0,
        "phoneCode": "\u002B685",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 175
    },
    {
        "name": "San Marino",
        "code": "sm",
        "flag": 0,
        "phoneCode": "\u002B378",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 176
    },
    {
        "name": "S\u00E3o Tom\u00E9 and Pr\u00EDncipe",
        "code": "st",
        "flag": 0,
        "phoneCode": "\u002B239",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 177
    },
    {
        "name": "Saudi Arabia",
        "code": "sa",
        "flag": 0,
        "phoneCode": "\u002B966",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 178
    },
    {
        "name": "Senegal",
        "code": "sn",
        "flag": 0,
        "phoneCode": "\u002B221",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 179
    },
    {
        "name": "Serbia",
        "code": "rs",
        "flag": 0,
        "phoneCode": "\u002B381",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 180
    },
    {
        "name": "Seychelles",
        "code": "sc",
        "flag": 0,
        "phoneCode": "\u002B248",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 181
    },
    {
        "name": "Sierra Leone",
        "code": "sl",
        "flag": 0,
        "phoneCode": "\u002B232",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 182
    },
    {
        "name": "Singapore",
        "code": "sg",
        "flag": 0,
        "phoneCode": "\u002B65",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 183
    },
    {
        "name": "Sint Maarten",
        "code": "sx",
        "flag": 0,
        "phoneCode": "\u002B1",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 184
    },
    {
        "name": "Slovakia",
        "code": "sk",
        "flag": 0,
        "phoneCode": "\u002B421",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 185
    },
    {
        "name": "Slovenia",
        "code": "sl",
        "flag": 0,
        "phoneCode": "\u002B386",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 186
    },
    {
        "name": "Solomon Islands",
        "code": "sb",
        "flag": 0,
        "phoneCode": "\u002B677",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 187
    },
    {
        "name": "South Africa",
        "code": "za",
        "flag": 0,
        "phoneCode": "\u002B27",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 188
    },
    {
        "name": "South Korea",
        "code": "kr",
        "flag": 0,
        "phoneCode": "\u002B82",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 189
    },
    {
        "name": "South Sudan",
        "code": "ss",
        "flag": 0,
        "phoneCode": "\u002B211",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 190
    },
    {
        "name": "Spain",
        "code": "es",
        "flag": 0,
        "phoneCode": "\u002B34",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 191
    },
    {
        "name": "Sri Lanka",
        "code": "lk",
        "flag": 0,
        "phoneCode": "\u002B94",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 192
    },
    {
        "name": "St. Barth\u00E9lemy",
        "code": "bl",
        "flag": 0,
        "phoneCode": "\u002B590",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 193
    },
    {
        "name": "St. Helena",
        "code": "sh",
        "flag": 0,
        "phoneCode": "\u002B290",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 194
    },
    {
        "name": "St. Kitts \u0026 Nevis",
        "code": "kn",
        "flag": 0,
        "phoneCode": "\u002B1",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 195
    },
    {
        "name": "St. Lucia",
        "code": "lc",
        "flag": 0,
        "phoneCode": "\u002B1",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 196
    },
    {
        "name": "St. Martin",
        "code": "mf",
        "flag": 0,
        "phoneCode": "\u002B590",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 197
    },
    {
        "name": "St. Pierre \u0026 Miquelon",
        "code": "pm",
        "flag": 0,
        "phoneCode": "\u002B508",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 198
    },
    {
        "name": "St. Vincent \u0026 Grenadines",
        "code": "vc",
        "flag": 0,
        "phoneCode": "\u002B1",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 199
    },
    {
        "name": "Sudan",
        "code": "sd",
        "flag": 0,
        "phoneCode": "\u002B249",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 200
    },
    {
        "name": "Suriname",
        "code": "sr",
        "flag": 0,
        "phoneCode": "\u002B597",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 201
    },
    {
        "name": "Sweden",
        "code": "se",
        "flag": 0,
        "phoneCode": "\u002B46",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 202
    },
    {
        "name": "Switzerland",
        "code": "ch",
        "flag": 0,
        "phoneCode": "\u002B41",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 203
    },
    {
        "name": "Syria",
        "code": "sy",
        "flag": 0,
        "phoneCode": "\u002B963",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 204
    },
    {
        "name": "Taiwan (China)",
        "code": "tw",
        "flag": 0,
        "phoneCode": "\u002B886",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 205
    },
    {
        "name": "Tajikistan",
        "code": "tj",
        "flag": 0,
        "phoneCode": "\u002B992",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 206
    },
    {
        "name": "Tanzania",
        "code": "tz",
        "flag": 0,
        "phoneCode": "\u002B255",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 207
    },
    {
        "name": "Thailand",
        "code": "th",
        "flag": 0,
        "phoneCode": "\u002B66",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 208
    },
    {
        "name": "Timor-Leste",
        "code": "tl",
        "flag": 0,
        "phoneCode": "\u002B670",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 209
    },
    {
        "name": "Togo",
        "code": "tg",
        "flag": 0,
        "phoneCode": "\u002B228",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 210
    },
    {
        "name": "Tokelau",
        "code": "tk",
        "flag": 0,
        "phoneCode": "\u002B690",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 211
    },
    {
        "name": "Tonga",
        "code": "to",
        "flag": 0,
        "phoneCode": "\u002B676",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 212
    },
    {
        "name": "Trinidad \u0026 Tobago",
        "code": "tt",
        "flag": 0,
        "phoneCode": "\u002B1",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 213
    },
    {
        "name": "Tunisia",
        "code": "tn",
        "flag": 0,
        "phoneCode": "\u002B216",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 214
    },
    {
        "name": "Turkey",
        "code": "tr",
        "flag": 0,
        "phoneCode": "\u002B90",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 215
    },
    {
        "name": "Turkmenistan",
        "code": "tm",
        "flag": 0,
        "phoneCode": "\u002B993",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 216
    },
    {
        "name": "Turks \u0026 Caicos Islands",
        "code": "tc",
        "flag": 0,
        "phoneCode": "\u002B1",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 217
    },
    {
        "name": "Tuvalu",
        "code": "tv",
        "flag": 0,
        "phoneCode": "\u002B688",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 218
    },
    {
        "name": "U.S. Virgin Islands",
        "code": "vi",
        "flag": 0,
        "phoneCode": "\u002B1",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 219
    },
    {
        "name": "Uganda",
        "code": "ug",
        "flag": 0,
        "phoneCode": "\u002B256",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 220
    },
    {
        "name": "Ukraine",
        "code": "ua",
        "flag": 0,
        "phoneCode": "\u002B380",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 221
    },
    {
        "name": "United Arab Emirates",
        "code": "ae",
        "flag": 0,
        "phoneCode": "\u002B971",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 222
    },
    {
        "name": "United Kingdom",
        "code": "gb",
        "flag": 0,
        "phoneCode": "\u002B44",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 223
    },
    {
        "name": "United States",
        "code": "us",
        "flag": 0,
        "phoneCode": "\u002B1",
        "phoneFormat": "STR(,[1-9],\\d,\\d,STR),STR ,\\d,\\d,\\d,STR-,\\d,\\d,\\d,\\d",
        "hasState": true,
        "hasProvince": false,
        "isDefault": true,
        "isPriority": true,
        "id": 224
    },
    {
        "name": "Uruguay",
        "code": "uy",
        "flag": 0,
        "phoneCode": "\u002B598",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 225
    },
    {
        "name": "Uzbekistan",
        "code": "uz",
        "flag": 0,
        "phoneCode": "\u002B998",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 226
    },
    {
        "name": "Vanuatu",
        "code": "vu",
        "flag": 0,
        "phoneCode": "\u002B678",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 227
    },
    {
        "name": "Vatican City",
        "code": "va",
        "flag": 0,
        "phoneCode": "\u002B39",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 228
    },
    {
        "name": "Venezuela",
        "code": "ve",
        "flag": 0,
        "phoneCode": "\u002B58",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 229
    },
    {
        "name": "Vietnam",
        "code": "vn",
        "flag": 0,
        "phoneCode": "\u002B84",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 230
    },
    {
        "name": "Wallis \u0026 Futuna",
        "code": "wf",
        "flag": 0,
        "phoneCode": "\u002B681",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 231
    },
    {
        "name": "Yemen",
        "code": "ye",
        "flag": 0,
        "phoneCode": "\u002B967",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 232
    },
    {
        "name": "Zambia",
        "code": "zm",
        "flag": 0,
        "phoneCode": "\u002B260",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 233
    },
    {
        "name": "Zimbabwe",
        "code": "zw",
        "flag": 0,
        "phoneCode": "\u002B263",
        "phoneFormat": "",
        "hasState": false,
        "hasProvince": false,
        "isDefault": false,
        "isPriority": false,
        "id": 234
    }
];