import { t } from 'i18next';

export const languageData = [

    {
        locale: 'en',
        translation: {
            Create_Your_Free_Account: `Create Your Free Account`,
            Welcome_to_247PRO: "Welcome to 247PRO",
            Welcome_To: "Welcome to",
            Please_provide_your_login_information: "Please provide your login information",
            Full_name: "Full name",
            Email: "Email",
            Next: "Next",
            Password: "Password",
            Login: `Login Your Account`,
            logintText: "Login",
            verifyBuisnessHeader: 'Help us to improve your experience by answering a few questions',
            Are_you_a_business: 'Are you a business?',
            yes: 'Yes',
            no: 'No',
            completeQuestions: `Complete these questions to receive job leads.`,
            Industry: "Industry",
            primarySpecialty: "Primary specialty",
            JobType: "Job type",
            ZipCode: "Zip code",
            MobilePhone: "Mobile phone",
            CompleteRegisration: "Complete Regisration",
            Verify: "Verify",
            RESEND_CODE: "RESEND CODE",
            resentText: "If you didn’t receive the code. Please click the button below.",
            enter_Code_Text: 'Enter 4 digit code sent to your mobile +1 (234) 567 8900.',
            Verify_Your_Mobile: "Verify Your Mobile",
            Forget_your_password: "Forget your password?",
            resetInfoMsg: "To reset your password please provide the information below.",
            Reset_Password: "Reset Password",
            Email_or_phone: "Email or phone",
            Remember_you_password: "Remember you password?",
            Get_your_code: "Get your code",
            Verify_Proceed: "Verify & Proceed",
            Code_has_been_sent_to_your_phone_number: 'Code has been sent to your phone number.',
            Code_has_been_sent_to_your_EmailAddress: 'Code has been sent to your email address.',
            Set_your_password: "Set your password.",

            newPassMsg: `Your new password must be different from your previous password used`,
            New_password: "New password",
            Confirm_password: "Confirm password",
            Continue: "Continue",
            Phone_or_email: "Phone or email",
            Forget_Password: 'Forget Password',
            Remember_me: "Remember me",
            Continue_with_google: "Continue with google",
            Continue_with_Apple: "Continue with Apple",
            New_here: "New here? ",
            Create_an_free_account: "Create an free account ",
            or: "or",
            Whats_your_mobile_number: "What’s your mobile number?",
            Enter_Your_Email: "Enter Your Email",
            Mobile_phone_number: "Mobile phone number",
            AgreeTo: `By signing up, I agree to 247Pro’s`,
            TermsAndConditions: "Terms & Conditions.",
            Already_have_an_account: 'Already have an account? ',
            Marketplace: "Marketplace",
            SearchJobs: "Search jobs",
            UsemyProFindersavedleadpreferences: "Use my Pro Finder saved lead preferences",
            AdHocPreferences: "Ad-Hoc Preferences",
            RESET: "RESET",
            Jobtype: "Job type",
            Specialty: "Specialty",
            Location: 'Location',
            ApplyFilter: "Apply Filter",
            Majorrennovationforasinglefamilyhome: "Major rennovation for a single family home",
            marketPlaceMsg: "Hello all, I am looking for a contractor for my kitchen, I am looking for someone who can do my kitchen Thank you.",
            BurlingameCA: "Burlingame, CA",
            Cancel: "Cancel",
            Done: "Done",
            Construction: "Construction",
            Marketing: `Marketing`,
            Sales: "Sales",
            Software: "Software",
            All: "All",
            Plumbing: "Plumbing",
            Electrical: "Electrical",
            KitchenSink: "Kitchen sink",
            InstallAfaucet: "Install a faucet",
            InstallAsink: "Install a sink",
            InstallAtoilet: "Install a toilet",
            Tub: "Tub",
            WaterHeater: 'Water heater',
            Cities: "Cities",
            RadiussearchlimitedtotheUnitedStates: "Radius search limited to the United States",
            Searchorcreatenewcity: "Search or create new city",
            Radius: "Radius",
            PostaJob: "Post a Job",
            LeadPreference: "Lead Preference",
            MyFavorJobs: "My Favor Jobs",
            JobDescription: "Job Description",
            JobDescriptionMsg: "I like to do a whole house renovation, including one kitchen I like to do a whole house renovation, including one kitchen like to do a whole house renovation, including one one one one one one one one ",
            Attachments: "Attachments",
            ACCEPTTOBID: "ACCEPT TO BID",
            Congratulationsandgoodluckonyourbidding: "Congratulations and good luck on your bidding.",
            Createbidlater: "Create bid later",
            Setmatchingcriteriasforjobopportunities: "Set matching criterias for job opportunities",
            Theindustriesyouwillreceivejobleadsfrom: "The industries you will receive job leads from",
            IndustryPreferences: "Industry Preferences",
            CREATEABCINDUSTRY: "CREATE “ABC” INDUSTRY",
            Norecordfound: "No record found",
            BusinessCard: "Business Card",
            AddNewCart: "Add New Cart",
            Delete: "Delete",
            Edit: "Edit",
            Share: "Share",
            Copycardlink: "Copy card link",
            SaveQRtoPhotos: "Save QR to Photos",
            ShareQRviaEmail: "Share QR via Email",
            Shareanotherway: "Share another way",
            ShareCardviaText: "Share Card via Text",
            ShareCard: "Share Card",
            SaveContact: "Save Contact",
            Contactissavedtoandyour: "Contact is saved to 247PRO and your",
            CreateYourFreeBusinessCard: "Create Your Free Business Card",
            phoneContacts: "phone Contacts",
            alreadysavedinyourcontacts: "already saved in your contacts",
            NewBusinessCard: "New Business Card",
            firstname: "First name",
            lastName: "Last name",
            about: "about",
            EMail: "E-mail",
            ContactInfo: 'Contact Info',
            Website: 'Website',
            StreetAddress: "Street address",
            AddCustomField: "Add Custom Field",
            SocialProfile: "Social Profile",
            AddSocialAccount: "Add Social Account",
            GreenMetroInc: "Green Metro Inc",
            Invite: "Invite",
            ApplicationsOrder: "Applications Order",
            Applications: "Applications",
            hideshow: "(hide/show)",
            BizCards: 'Biz Cards',
            BizCard: 'Biz Card',
            Calendar: "Calendar",
            Contacts: "Contacts",
            Events: "Events",
            Timeclock: "Timeclock",
            Members: "Members",
            Tasks: "Tasks",
            AccountAndSettings: "Account & Settings",
            CompanyProfile: 'Company Profile',
            AccountSettings: "Account Settings",
            ApplicaionSettings: "Applicaion Settings",
            Youhavenocontact: "You have no contact",
            search: "search",
            Company: "Company (200)",
            AddContact: "Add Contact",
            ConnectionRequests: "Connection Requests",
            Contacttype: "Contact type",
            NewContact: "New Contact",
            Companyname: "Company name",
            Speciality: 'Speciality',
            jobTitle: 'job title',
            Websiteurl: "Website url",
            SHOWMORE: "SHOW MORE",
            country: "country",
            StreetAddressLine2: "Street address line 2",
            City: "City",
            State: "State",
            PObox: "PO box",
            Label: "Label",
            Linktocompany: "Link to company",
            SelectAcompany: "Select a company",
            Attachment: "Attachment",
            SHOWLESS: "SHOW LESS",
            AddCompany: "Add Company",
            NewCompany: "New Company",
            Contactperson: "Contact person",
            Notes: "Notes",
            Entitytype: "Entity type",
            Staff: "Staff",
            Revenue: "Revenue",
            Address: "Address",
            Title: "Title",
            Capturenew: "Capture new",
            Uploadfromgallery: "Upload from gallery",
            mile: "mile",
            FilterCompany: "Filter Company",
            ClearFilters: "Clear Filters",
            Import: "Import",
            company: "Company",
            Allow247protoaccessphotosmediaandfilesonyourdevice: "Allow 247pro to access photos, media and files on your device.",
            Deny: "Deny",
            Allow: "Allow",
            Files: "Files",
            Client: "Client",
            Emailaddress: "Email address",
            Nocompanylinked: "No company linked",
            NoCompanyName: "No Company Name",
            Generalcontractor: "General contractor",
            FromGreenMetroInc: "From Green Metro Inc.",
            Overview: "Overview",
            QRCode: "QR Code",
            Services: 'Services',
            Photos: "Photos",
            Reviews: "Reviews",
            Kitchenremodel: "Kitchen remodel",
            Bathroomremodel: "Bathroom remodel",
            AdditionsKitchenremodel: "Additions Kitchen remodel",
            Painting: "Painting",
            Electricalworks: "Electrical works",
            Painter: "Painter",
            Electrician: 'Electrician',
            twentyFiveReviews: "25 Reviews",
            ayearago: "a year ago",
            CopyQrCode:'Copy Qr Code',
            CompanyQRCode:"Company QR Code",
            EditCompanyProfile:"Edit Company Profile",

        }
    },
    {
        locale: 'ch',
        translation: {
            Create_Your_Free_Account: `创建您的免费帐户`,
            Please_provide_your_login_information: "请提供您的登录信息",
            Full_name: "全名",
            verifyBuisnessHeader: '回答几个问题帮助我们改善您的体验',
            Are_you_a_business: '你是企业吗？',
            Email: "电子邮件",
            Next: "下一步",
            Password: "密码",
            Welcome_to_247PRO: "欢迎来到247PRO",
            Login: `登录您的帐户`,
            yes: '是的',
            no: '不',
            completeQuestions: `完成这些问题以获得工作机会。`,
            Industry: "行业",
            primarySpecialty: "主要专业",
            JobType: "工作类型",
            MobilePhone: "邮政编码",
            CompleteRegisration: "完成注册",
            Verify: "核实",
            ZipCode: "邮政编码",
            RESEND_CODE: "重新发送验证码",
            resentText: "如果您没有收到代码。 请点击下面的按钮。",
            enter_Code_Text: '输入发送至您手机 +1 (234) 567 8900 的 4 位数代码。',

            Verify_Your_Mobile: "验证您的手机",
            Forget_your_password: "忘记密码？",
            resetInfoMsg: "要重置您的密码，请提供以下信息。",
            Reset_Password: "重设密码",
            Email_or_phone: "邮件或者电话",

            Remember_you_password: "还记得你的密码吗？",
            logintText: "登录",
            Get_your_code: "获取您的代码",
            Code_has_been_sent_to_your_phone_number: '代码已发送至您的电话号码',
            Verify_Proceed: "验证并继续",
            Code_has_been_sent_to_your_EmailAddress: '代码已发送至您的电子邮件地址。',
            Set_your_password: "设置你的密码。",
            newPassMsg: `您的新密码必须与之前使用的密码不同。`,
            New_password: "新密码",
            Confirm_password: "确认密码",
            Continue: "继续",
            Phone_or_email: "电话还是邮件",

            Welcome_To: "欢迎来到",
            Forget_Password: '忘记密码',
            Remember_me: "记住账号",
            Continue_with_google: "继续使用谷歌",
            Continue_with_Apple: "继续使用苹果",

            New_here: "新来的？",
            Create_an_free_account: "创建一个免费帐户",
            or: "或者",
            Whats_your_mobile_number: "你手机号码多少？",
            Enter_Your_Email: "输入你的电子邮箱",

            Mobile_phone_number: "手机号码",
            AgreeTo: `注册即表示我同意 247Pro 的`,
            TermsAndConditions: "条款和条件。",
            Already_have_an_account: '已经有帐户？',
            Marketplace: "市场",
            SearchJobs: "搜索职位",
            UsemyProFindersavedleadpreferences: "使用我的 Pro Finder 保存的潜在客户首选项",
            AdHocPreferences: "临时首选项",
            RESET: "重置",
            Jobtype: "工作类型",
            Specialty: "专业",
            Location: '地点',
            ApplyFilter: "应用过滤器",
            Majorrennovationforasinglefamilyhome: "单一家庭住宅的重大翻新",
            marketPlaceMsg: "大家好，我正在寻找一个厨房承包商，我正在寻找可以做我的厨房的人，谢谢。",
            BurlingameCA: "加利福尼亚州伯林格姆",
            Cancel: "取消",
            Done: "完毕",
            Construction: "建造",
            Marketing: `营销`,
            Sales: "销售量",
            Software: "软件",
            All: "全部",
            Plumbing: "水暖",
            Electrical: "电气",
            KitchenSink: "厨房水槽",
            InstallAfaucet: "安装水龙头",
            InstallAsink: "安装水槽",
            InstallAtoilet: "安装厕所",
            Tub: "浴缸",
            WaterHeater: '热水器',
            Cities: "城市",
            RadiussearchlimitedtotheUnitedStates: "半径搜索仅限于美国",
            Searchorcreatenewcity: "搜索或创建新城市",
            Radius: "半径",
            PostaJob: "发布职位",
            LeadPreference: "潜在客户偏好",
            MyFavorJobs: "我最喜欢的工作",
            JobDescription: "职位描述",
            JobDescriptionMsg: "我喜欢做全屋装修，包括一间厨房 我喜欢做全屋装修，包括一间厨房 我喜欢做全屋装修，包括一一一一一一一一",
            BizCards: '名片',
            Calendar: "日历",
            Tasks: "任务",

            Attachments: "附件",
            ACCEPTTOBID: "接受投标",
            Congratulationsandgoodluckonyourbidding: "恭喜您并祝您投标顺利。",
            Createbidlater: "稍后创建出价",
            Setmatchingcriteriasforjobopportunities: "设定工作机会的匹配标准",
            Theindustriesyouwillreceivejobleadsfrom: "您将收到工作机会的行业",
            IndustryPreferences: "行业偏好",
            Norecordfound: "行业偏好",
            CREATEABCINDUSTRY: "打造“ABC”产业",
            BusinessCard: "名片",
            AddNewCart: "添加新购物车",
            Delete: "删除",
            Share: "分享",
            Edit: "编辑",
            Copycardlink: "复制卡链接",
            SaveQRtoPhotos: "将二维码保存到照片",
            ShareQRviaEmail: "通过电子邮件分享二维码",
            Shareanotherway: "分享另一种方式",
            ShareCardviaText: "通过短信分享卡",
            ShareCard: "共享卡",
            SaveContact: "保存联系方式",
            CreateYourFreeBusinessCard: "创建您的免费名片",
            Contactissavedtoandyour: "联系人信息将保存至 247PRO，并且您的",
            phoneContacts: "电话 联系方式",
            alreadysavedinyourcontacts: "已保存在您的通讯录中",
            NewBusinessCard: "新名片",
            firstname: "名",
            lastName: "姓",
            about: "关于",
            EMail: "电子邮件",
            ContactInfo: '联系方式',
            Website: '网站',
            StreetAddress: "街道地址",
            AddCustomField: "添加自定义字段",
            SocialProfile: "社会概况",
            AddSocialAccount: "添加社交帐户",
            GreenMetroInc: "绿色地铁公司",
            Invite: "邀请",
            ApplicationsOrder: "申请订单",
            Applications: "应用领域",
            hideshow: "（隐藏/显示）",
            Contacts: "联系方式",
            Events: "活动",
            Timeclock: "时钟",
            Members: "会员",
            AccountAndSettings: "帐号设定",
            CompanyProfile: '公司简介',
            AccountSettings: "帐号设定",
            BizCard: '名片卡',
            ApplicaionSettings: "应用程序设置",
            Youhavenocontact: "你没有联系方式",
            search: "搜索",
            Company: "公司 (200)",
            AddContact: "增加联系人",
            ConnectionRequests: "连接请求",
            NewContact: "新联系人",
            Contacttype: "触点类型",
            Companyname: "公司名称",
            Speciality: '专业',
            jobTitle: '职称',
            Websiteurl: "网址",
            SHOWMORE: "展示更多",
            country: "国家",
            StreetAddressLine2: "街道地址第 2 行",
            City: "城市",
            State: "状态",
            PObox: "邮政信箱",
            Label: "标签",
            Linktocompany: "链接至公司",
            SelectAcompany: "选择公司",
            Attachment: "依恋",
            SHOWLESS: "显示较少",
            AddCompany: "添加公司",
            NewCompany: "新公司",
            Contactperson: "联络人",
            Entitytype: "实体类型",
            Staff: "职员",

            Notes: "笔记",
            Revenue: "收入",
            Address: "地址",
            Title: "标题",
            Capturenew: "捕捉新的",
            Uploadfromgallery: "从图库上传",
            mile: "英里",
            ClearFilters: "清除过滤器",
            FilterCompany: "过滤器公司",
            company: "公司",
            Import: "进口",
            Allow247protoaccessphotosmediaandfilesonyourdevice: "允许 247pro 访问您设备上的照片、媒体和文件。",
            Deny: "否定",
            Allow: "允许",
            Files: "文件",
            Client: "客户",
            Emailaddress: "电子邮件地址",
            Nocompanylinked: "没有公司LinkedIn",
            NoCompanyName: "无公司名称",
            Generalcontractor: "总承包人",
            FromGreenMetroInc: "来自绿色地铁公司",
            QRCode: "二维码",
            Overview: "概述",
            Services: '服务',
            Photos: "相片",
            Reviews: "评论",
            Kitchenremodel: "厨房改造",
            Bathroomremodel: "浴室改造",
            AdditionsKitchenremodel: "厨房改造加建",
            Painting: "绘画",
            Electricalworks: "电力工程",
            Electrician: '电工',
            Painter: "画家",
            twentyFiveReviews: "25 条评论",
            ayearago: "一年前",
            CopyQrCode:'复制二维码',
            CompanyQRCode:"公司二维码",
            EditCompanyProfile:"编辑公司简介",

        }
    },
    {
        locale: 'es',
        translation: {
            Create_Your_Free_Account: `Crea tu cuenta gratuita`,
            Welcome_to_247PRO: "Bienvenido a 247PRO",
            Please_provide_your_login_information: "Por favor proporcione su información de inicio de sesión",
            Login: `inicie sesión en su cuenta`,
            Password: "Contraseña",
            verifyBuisnessHeader: 'Ayúdanos a mejorar tu experiencia respondiendo algunas preguntas',
            Next: "Siguiente",
            Full_name: "Nombre completo",
            Email: "Correo electrónico",
            Are_you_a_business: '¿Eres un negocio?',
            yes: 'Sí',
            no: 'No',
            completeQuestions: `Complete estas preguntas para recibir oportunidades de trabajo.`,
            Industry: "Industria",
            primarySpecialty: "especialidad primaria",
            JobType: "El tipo de trabajo",
            ZipCode: "Código postal",
            MobilePhone: "Código postal",
            CompleteRegisration: "Registro completo",
            Verify: "Verificar",
            RESEND_CODE: "REENVIAR CODIGO",
            resentText: "Si no recibiste el código. Por favor, haga clic en el botón de abajo.",
            enter_Code_Text: 'Ingresa el código de 4 dígitos enviado a tu móvil +1 (234) 567 8900.',
            Verify_Your_Mobile: "Verifica tu móvil",
            Forget_your_password: "¿Olvidaste tu contraseña?",
            resetInfoMsg: "Para restablecer su contraseña, proporcione la información a continuación.",
            Reset_Password: "Restablecer la contraseña",
            Email_or_phone: "Email o teléfono",
            Remember_you_password: "¿Recuerdas tu contraseña?",
            logintText: "Acceso",
            Get_your_code: "Consigue tu código",
            Code_has_been_sent_to_your_phone_number: 'El código ha sido enviado a su número de teléfono',
            Verify_Proceed: "Verificar y continuar",
            Code_has_been_sent_to_your_EmailAddress: 'El código ha sido enviado a su dirección de correo electrónico.',
            newPassMsg: `Su nueva contraseña debe ser diferente de su contraseña anterior utilizada.`,
            Set_your_password: "Establece tu contraseña.",
            New_password: "Nueva contraseña",
            Confirm_password: "Confirmar Contraseña",
            Continue: "Continuar",
            Phone_or_email: "Teléfono o correo electrónico",
            Welcome_To: "Bienvenida a",
            Forget_Password: 'Contraseña olvidada',

            Remember_me: "Acuérdate de mí",
            Continue_with_google: "continuar con google",
            Continue_with_Apple: "Continuar con Apple",
            Create_an_free_account: "Crea una cuenta gratis",
            New_here: "Nueva aquí?",
            or: "o",
            Whats_your_mobile_number: "¿Cual es tu numero de móvil?",
            Mobile_phone_number: "Número de teléfono móvil",
            Enter_Your_Email: "Introduce tu correo electrónico",
            AgreeTo: `Al registrarme, acepto las condiciones de 247Pro`,
            TermsAndConditions: "Términos y condiciones.",
            Already_have_an_account: '¿Ya tienes una cuenta? ',
            Marketplace: "Mercado",
            SearchJobs: "Buscar empleos",
            UsemyProFindersavedleadpreferences: "Usar mis preferencias de clientes potenciales guardadas en Pro Finder",
            AdHocPreferences: "Preferencias ad hoc",
            RESET: "REINICIAR",
            Jobtype: "El tipo de trabajo",
            Specialty: "Especialidad",
            Location: 'Ubicación',
            ApplyFilter: "Aplicar filtro",
            Majorrennovationforasinglefamilyhome: "Renovación importante para una vivienda unifamiliar.",
            marketPlaceMsg: "Hola a todos, estoy buscando un contratista para mi cocina, estoy buscando alguien que pueda hacer mi cocina. Gracias.",
            BurlingameCA: "Burlingame, California, EE.UU.",
            Cancel: "Cancelar",
            Construction: "Construcción",
            Done: "Hecho",
            Marketing: `Marketing`,
            Sales: "Ventas",
            Software: "Software",
            All: "Toda",
            Plumbing: "Plomería",
            Electrical: "Eléctrica",
            KitchenSink: "Fregadero",
            InstallAfaucet: "instalar un grifo",
            InstallAsink: "instalar un fregadero",
            InstallAtoilet: "instalar un baño",
            Tub: "Bañera",
            WaterHeater: 'Calentador de agua',
            Cities: "Ciudades",
            RadiussearchlimitedtotheUnitedStates: "Búsqueda de radio limitada a los Estados Unidos",
            Searchorcreatenewcity: "Buscar o crear una nueva ciudad",
            PostaJob: "Anunciar un trabajo",
            Radius: "Radio",
            LeadPreference: "Preferencia de cliente potencial",
            MyFavorJobs: "Mis trabajos favoritos",
            JobDescription: "Descripción del trabajo",
            JobDescriptionMsg: "Me gusta hacer una renovación completa de la casa, incluida una cocina Me gusta hacer una renovación completa de la casa, incluida una cocina Me gusta hacer una renovación completa de la casa, incluida una uno uno uno uno uno uno uno",
            Attachments: "Archivos adjuntos",
            ACCEPTTOBID: "ACEPTAR OFERTA",
            Congratulationsandgoodluckonyourbidding: "Felicitaciones y buena suerte con su oferta.",
            Createbidlater: "Crear oferta más tarde",
            Setmatchingcriteriasforjobopportunities: "Establecer criterios coincidentes para las oportunidades laborales",
            Theindustriesyouwillreceivejobleadsfrom: "Las industrias de las que recibirá oportunidades de empleo",
            IndustryPreferences: "Preferencias de la industria",
            Norecordfound: "Preferencias de la industria",
            CREATEABCINDUSTRY: "CREAR LA INDUSTRIA “ABC”",
            BusinessCard: "Tarjeta de visita",
            AddNewCart: "Agregar nuevo carrito",
            Delete: "Borrar",
            Share: "Compartir",
            Edit: "Editar",
            Copycardlink: "Copiar enlace de tarjeta",
            SaveQRtoPhotos: "Guardar QR en fotos",
            ShareQRviaEmail: "Compartir QR por correo electrónico",
            Shareanotherway: "Comparte de otra manera",
            ShareCardviaText: "Compartir tarjeta por mensaje de texto",
            ShareCard: "Compartir tarjeta",
            SaveContact: "Guardar contacto",
            CreateYourFreeBusinessCard: "Crea tu tarjeta de presentación gratuita",
            Contactissavedtoandyour: "El contacto se guarda en 247PRO y su",
            phoneContacts: "Contactos telefonicas",
            alreadysavedinyourcontacts: "ya guardado en tus contactos",
            Invite: "Invitar",
            NewBusinessCard: "Nueva tarjeta de presentación",
            firstname: "Nombre de pila",
            lastName: "Apellido",
            about: "acerca de",
            EMail: "Correo electrónico",
            ContactInfo: 'Datos de contacto',
            Website: 'Sitio web',
            StreetAddress: "Dirección",
            AddCustomField: "Agregar campo personalizado",
            SocialProfile: "Perfil social",
            AddSocialAccount: "Agregar cuenta social",
            GreenMetroInc: "Metro Verde Inc.",
            ApplicationsOrder: "Orden de aplicaciones",
            Applications: "Aplicaciones",
            hideshow: "(ocultar mostrar)",
            BizCards: 'Tarjetas de visita',
            Calendar: "Calendario",
            Contacts: "Contactos",
            Events: "Eventos",
            Timeclock: "reloj de tiempo",
            Members: "Miembros",
            Tasks: "Tareas",
            AccountAndSettings: "Configuraciones de la cuenta",
            CompanyProfile: 'Perfil de la empresa',
            AccountSettings: "Configuraciones de la cuenta",
            BizCard: 'Tarjeta de visita',
            ApplicaionSettings: "Configuraciones de la aplicación",
            Youhavenocontact: "no tienes contacto",
            search: "buscar",
            Company: "Empresa (200)",
            AddContact: "Agregar contacto",
            ConnectionRequests: "Solicitudes de conexión",
            NewContact: "Nuevo contacto",
            Contacttype: "Tipo de Contacto",
            Companyname: "Nombre de empresa",
            Speciality: 'Especialidad',
            jobTitle: 'título profesional',
            Websiteurl: "URL del sitio web",
            SHOWMORE: "MOSTRAR MÁS",
            country: "país",
            StreetAddressLine2: "Dirección de calle Linea 2",
            City: "Ciudad",
            State: "Estado",
            PObox: "apartado postal",
            Label: "Etiqueta",
            Linktocompany: "Enlace a la empresa",
            SelectAcompany: "Seleccione una empresa",
            Attachment: "Adjunto",
            SHOWLESS: "MUESTRA MENOS",
            AddCompany: "Agregar empresa",
            NewCompany: "Nueva compañia",
            Contactperson: "Persona de contacto",
            Notes: "Notas",
            Entitytype: "Tipo de entidad",
            Staff: "Personal",
            Revenue: "Ganancia",
            Address: "DIRECCIÓN",
            Title: "Título",
            Capturenew: "Capturar nueva",
            Uploadfromgallery: "Subir desde la galería",
            mile: "milla",
            ClearFilters: "Borrar filtros",
            FilterCompany: "Filtrar empresa",
            company: "Compañía",
            Import: "Importar",
            Deny: "Denegar",
            Allow247protoaccessphotosmediaandfilesonyourdevice: "Permita que 247pro acceda a fotos, medios y archivos en su dispositivo.",
            Allow: "Permitir",
            Files: "Archivos",
            Client: "Cliente",
            Emailaddress: "Dirección de correo electrónico",
            Nocompanylinked: "Ninguna empresa linkedin",
            NoCompanyName: "Sin nombre de empresa",
            Generalcontractor: "Contratista general",
            FromGreenMetroInc: "De Green Metro Inc.",
            QRCode: "Código QR",
            Overview: "Descripción general",
            Services: 'Servicios',
            Photos: "Fotos",
            Reviews: "Reseñas",
            Kitchenremodel: "remodelación de cocina",
            Bathroomremodel: "remodelación del baño",
            AdditionsKitchenremodel: "Adiciones remodelación de cocina",
            Painting: "Cuadro",
            Electricalworks: "Obras eléctricas",
            Electrician: 'Electricista',
            Painter: "Pintora",
            twentyFiveReviews: "25 reseñas",
            ayearago: "Hace un año",
            CopyQrCode:'Copiar código QR',
            CompanyQRCode:"Código QR de la empresa",
            EditCompanyProfile:"Editar perfil de empresa",
        }
    }
];

export type languageProps = {
    id: string;
    name: string;
    code: string;
};

export const appLanguages: languageProps[] = [
    {
        id: '0',
        name: 'English',
        code: 'en'
    },
    {
        id: '1',
        name: 'chinese',
        code: 'ch'
    },
    {
        id: '5',
        name: 'Spanish',
        code: 'es'
    }
];
