import { t } from 'i18next';

export const languageData = [

    {
        locale: 'en',
        translation: {
            Create_Your_Free_Account: `Create Your Free Account`,
            Welcome_to_247PRO: "Welcome to 247PRO",
            Welcome_To: "Welcome to",
            Please_provide_your_login_information: "Please provide your login information",
            Full_name: "Full name",
            Email: "Email",
            Next: "Next",
            Password: "Password",
            Login: `Login Your Account`,
            logintText: "Login",
            verifyBuisnessHeader: 'Help us to improve your experience by answering a few questions',
            Are_you_a_business: 'Are you a business?',
            yes: 'Yes',
            no: 'No',
            completeQuestions: `Complete these questions to receive job leads.`,
            Industry: "Industry",
            primarySpecialty: "Primary specialty",
            JobType: "Job type",
            ZipCode: "Zip code",
            MobilePhone: "Mobile phone",
            CompleteRegisration: "Complete Regisration",
            Verify: "Verify",
            RESEND_CODE: "RESEND CODE",
            resentText: "If you didn’t receive the code. Please click the button below.",
            enter_Code_Text: 'Enter 4 digit code sent to your mobile +1 (234) 567 8900.',
            Verify_Your_Mobile: "Verify Your Mobile",
            Forget_your_password: "Forget your password?",
            resetInfoMsg: "To reset your password please provide the information below.",
            Reset_Password: "Reset Password",
            Email_or_phone: "Email or phone",
            Remember_you_password: "Remember you password?",
            Get_your_code: "Get your code",
            Verify_Proceed: "Verify & Proceed",
            Code_has_been_sent_to_your_phone_number: 'Code has been sent to your phone number.',
            Code_has_been_sent_to_your_EmailAddress: 'Code has been sent to your email address.',
            Set_your_password: "Set your password.",

            newPassMsg: `Your new password must be different from your previous password used`,
            New_password: "New password",
            Confirm_password: "Confirm password",
            Continue: "Continue",
            Phone_or_email: "Phone or email",
            Forget_Password: 'Forget Password',
            Remember_me: "Remember me",
            Continue_with_google: "Continue with google",
            Continue_with_Apple: "Continue with Apple",
            New_here: "New here? ",
            Create_an_free_account: "Create an free account ",
            or: "or",
            Whats_your_mobile_number: "What’s your mobile number?",
            Enter_Your_Email: "Enter Your Email",
            Mobile_phone_number: "Mobile phone number",
            AgreeTo: `By signing up, I agree to 247Pro’s`,
            TermsAndConditions: "Terms & Conditions.",
            Already_have_an_account: 'Already have an account? ',
            Marketplace: "Marketplace",
            SearchJobs: "Search jobs",
            UsemyProFindersavedleadpreferences: "Use my Pro Finder saved lead preferences",
            AdHocPreferences: "Ad-Hoc Preferences",
            RESET: "RESET",
            Jobtype: "Job type",
            Specialty: "Specialty",
            Location: 'Location',
            ApplyFilter: "Apply Filter",
            Majorrennovationforasinglefamilyhome: "Major rennovation for a single family home",
            marketPlaceMsg: "Hello all, I am looking for a contractor for my kitchen, I am looking for someone who can do my kitchen Thank you.",
            BurlingameCA: "Burlingame, CA",
            Cancel: "Cancel",
            Done: "Done",
            Construction: "Construction",
            Marketing: `Marketing`,
            Sales: "Sales",
            Software: "Software",
            All: "All",
            Plumbing: "Plumbing",
            Electrical: "Electrical",
            KitchenSink: "Kitchen sink",
            InstallAfaucet: "Install a faucet",
            InstallAsink: "Install a sink",
            InstallAtoilet: "Install a toilet",
            Tub: "Tub",
            WaterHeater: 'Water heater',
            Cities: "Cities",
            RadiussearchlimitedtotheUnitedStates: "Radius search limited to the United States",
            Searchorcreatenewcity: "Search or create new city",
            Radius: "Radius",
            PostaJob: "Post a Job",
            LeadPreference: "Lead Preference",
            MyFavorJobs: "My Favor Jobs",
            JobDescription: "Job Description",
            JobDescriptionMsg: "I like to do a whole house renovation, including one kitchen I like to do a whole house renovation, including one kitchen like to do a whole house renovation, including one one one one one one one one ",
            Attachments: "Attachments",
            ACCEPTTOBID: "ACCEPT TO BID",
            Congratulationsandgoodluckonyourbidding :"Congratulations and good luck on your bidding.",
            Createbidlater:"Create bid later",
            Setmatchingcriteriasforjobopportunities:"Set matching criterias for job opportunities",

        }
    },
    {
        locale: 'ch',
        translation: {
            Create_Your_Free_Account: `创建您的免费帐户`,
            Please_provide_your_login_information: "请提供您的登录信息",
            Full_name: "全名",
            verifyBuisnessHeader: '回答几个问题帮助我们改善您的体验',
            Are_you_a_business: '你是企业吗？',
            Email: "电子邮件",
            Next: "下一步",
            Password: "密码",
            Welcome_to_247PRO: "欢迎来到247PRO",
            Login: `登录您的帐户`,
            yes: '是的',
            no: '不',
            completeQuestions: `完成这些问题以获得工作机会。`,
            Industry: "行业",
            primarySpecialty: "主要专业",
            JobType: "工作类型",
            MobilePhone: "邮政编码",
            CompleteRegisration: "完成注册",
            Verify: "核实",
            ZipCode: "邮政编码",
            RESEND_CODE: "重新发送验证码",
            resentText: "如果您没有收到代码。 请点击下面的按钮。",
            enter_Code_Text: '输入发送至您手机 +1 (234) 567 8900 的 4 位数代码。',

            Verify_Your_Mobile: "验证您的手机",
            Forget_your_password: "忘记密码？",
            resetInfoMsg: "要重置您的密码，请提供以下信息。",
            Reset_Password: "重设密码",
            Email_or_phone: "邮件或者电话",

            Remember_you_password: "还记得你的密码吗？",
            logintText: "登录",
            Get_your_code: "获取您的代码",
            Code_has_been_sent_to_your_phone_number: '代码已发送至您的电话号码',
            Verify_Proceed: "验证并继续",
            Code_has_been_sent_to_your_EmailAddress: '代码已发送至您的电子邮件地址。',
            Set_your_password: "设置你的密码。",
            newPassMsg: `您的新密码必须与之前使用的密码不同。`,
            New_password: "新密码",
            Confirm_password: "确认密码",
            Continue: "继续",
            Phone_or_email: "电话还是邮件",

            Welcome_To: "欢迎来到",
            Forget_Password: '忘记密码',
            Remember_me: "记住账号",
            Continue_with_google: "继续使用谷歌",
            Continue_with_Apple: "继续使用苹果",

            New_here: "新来的？",
            Create_an_free_account: "创建一个免费帐户",
            or: "或者",
            Whats_your_mobile_number: "你手机号码多少？",
            Enter_Your_Email: "输入你的电子邮箱",

            Mobile_phone_number: "手机号码",
            AgreeTo: `注册即表示我同意 247Pro 的`,
            TermsAndConditions: "条款和条件。",
            Already_have_an_account: '已经有帐户？',
            Marketplace: "市场",
            SearchJobs: "搜索职位",
            UsemyProFindersavedleadpreferences: "使用我的 Pro Finder 保存的潜在客户首选项",
            AdHocPreferences: "临时首选项",
            RESET: "重置",
            Jobtype: "工作类型",
            Specialty: "专业",
            Location: '地点',
            ApplyFilter: "应用过滤器",
            Majorrennovationforasinglefamilyhome: "单一家庭住宅的重大翻新",
            marketPlaceMsg: "大家好，我正在寻找一个厨房承包商，我正在寻找可以做我的厨房的人，谢谢。",
            BurlingameCA: "加利福尼亚州伯林格姆",
            Cancel: "取消",
            Done: "完毕",
            Construction: "建造",
            Marketing: `营销`,
            Sales: "销售量",
            Software: "软件",
            All: "全部",
            Plumbing: "水暖",
            Electrical: "电气",
            KitchenSink: "厨房水槽",
            InstallAfaucet: "安装水龙头",
            InstallAsink: "安装水槽",
            InstallAtoilet: "安装厕所",
            Tub: "浴缸",
            WaterHeater: '热水器',
            Cities: "城市",
            RadiussearchlimitedtotheUnitedStates: "半径搜索仅限于美国",
            Searchorcreatenewcity: "搜索或创建新城市",
            Radius: "半径",
            PostaJob: "发布职位",
            LeadPreference: "潜在客户偏好",
            MyFavorJobs: "我最喜欢的工作",
            JobDescription: "职位描述",
            JobDescriptionMsg: "我喜欢做全屋装修，包括一间厨房 我喜欢做全屋装修，包括一间厨房 我喜欢做全屋装修，包括一一一一一一一一",

            Attachments: "附件",
            ACCEPTTOBID: "接受投标",
            Congratulationsandgoodluckonyourbidding :"恭喜您并祝您投标顺利。",
            Createbidlater:"稍后创建出价",
            Setmatchingcriteriasforjobopportunities:"设定工作机会的匹配标准",

        }
    },
    {
        locale: 'es',
        translation: {
            Create_Your_Free_Account: `Crea tu cuenta gratuita`,
            Welcome_to_247PRO: "Bienvenido a 247PRO",
            Please_provide_your_login_information: "Por favor proporcione su información de inicio de sesión",
            Login: `inicie sesión en su cuenta`,
            Password: "Contraseña",
            verifyBuisnessHeader: 'Ayúdanos a mejorar tu experiencia respondiendo algunas preguntas',
            Next: "Siguiente",
            Full_name: "Nombre completo",
            Email: "Correo electrónico",
            Are_you_a_business: '¿Eres un negocio?',
            yes: 'Sí',
            no: 'No',
            completeQuestions: `Complete estas preguntas para recibir oportunidades de trabajo.`,
            Industry: "Industria",
            primarySpecialty: "especialidad primaria",
            JobType: "El tipo de trabajo",
            ZipCode: "Código postal",
            MobilePhone: "Código postal",
            CompleteRegisration: "Registro completo",
            Verify: "Verificar",
            RESEND_CODE: "REENVIAR CODIGO",
            resentText: "Si no recibiste el código. Por favor, haga clic en el botón de abajo.",
            enter_Code_Text: 'Ingresa el código de 4 dígitos enviado a tu móvil +1 (234) 567 8900.',
            Verify_Your_Mobile: "Verifica tu móvil",
            Forget_your_password: "¿Olvidaste tu contraseña?",
            resetInfoMsg: "Para restablecer su contraseña, proporcione la información a continuación.",
            Reset_Password: "Restablecer la contraseña",
            Email_or_phone: "Email o teléfono",
            Remember_you_password: "¿Recuerdas tu contraseña?",
            logintText: "Acceso",
            Get_your_code: "Consigue tu código",
            Code_has_been_sent_to_your_phone_number: 'El código ha sido enviado a su número de teléfono',
            Verify_Proceed: "Verificar y continuar",
            Code_has_been_sent_to_your_EmailAddress: 'El código ha sido enviado a su dirección de correo electrónico.',
            newPassMsg: `Su nueva contraseña debe ser diferente de su contraseña anterior utilizada.`,
            Set_your_password: "Establece tu contraseña.",
            New_password: "Nueva contraseña",
            Confirm_password: "Confirmar Contraseña",
            Continue: "Continuar",
            Phone_or_email: "Teléfono o correo electrónico",
            Welcome_To: "Bienvenida a",
            Forget_Password: 'Contraseña olvidada',

            Remember_me: "Acuérdate de mí",
            Continue_with_google: "continuar con google",
            Continue_with_Apple: "Continuar con Apple",
            Create_an_free_account: "Crea una cuenta gratis",
            New_here: "Nueva aquí?",
            or: "o",
            Whats_your_mobile_number: "¿Cual es tu numero de móvil?",
            Mobile_phone_number: "Número de teléfono móvil",
            Enter_Your_Email: "Introduce tu correo electrónico",
            AgreeTo: `Al registrarme, acepto las condiciones de 247Pro`,
            TermsAndConditions: "Términos y condiciones.",
            Already_have_an_account: '¿Ya tienes una cuenta? ',
            Marketplace: "Mercado",
            SearchJobs: "Buscar empleos",
            UsemyProFindersavedleadpreferences: "Usar mis preferencias de clientes potenciales guardadas en Pro Finder",
            AdHocPreferences: "Preferencias ad hoc",
            RESET: "REINICIAR",
            Jobtype: "El tipo de trabajo",
            Specialty: "Especialidad",
            Location: 'Ubicación',
            ApplyFilter: "Aplicar filtro",
            Majorrennovationforasinglefamilyhome: "Renovación importante para una vivienda unifamiliar.",
            marketPlaceMsg: "Hola a todos, estoy buscando un contratista para mi cocina, estoy buscando alguien que pueda hacer mi cocina. Gracias.",
            BurlingameCA: "Burlingame, California, EE.UU.",
            Cancel: "Cancelar",
            Construction: "Construcción",
            Done: "Hecho",
            Marketing: `Marketing`,
            Sales: "Ventas",
            Software: "Software",
            All: "Toda",
            Plumbing: "Plomería",
            Electrical: "Eléctrica",
            KitchenSink: "Fregadero",
            InstallAfaucet: "instalar un grifo",
            InstallAsink: "instalar un fregadero",
            InstallAtoilet: "instalar un baño",
            Tub: "Bañera",
            WaterHeater: 'Calentador de agua',
            Cities: "Ciudades",
            RadiussearchlimitedtotheUnitedStates: "Búsqueda de radio limitada a los Estados Unidos",
            Searchorcreatenewcity: "Buscar o crear una nueva ciudad",
            PostaJob: "Anunciar un trabajo",
            Radius: "Radio",
            LeadPreference: "Preferencia de cliente potencial",
            MyFavorJobs: "Mis trabajos favoritos",
            JobDescription: "Descripción del trabajo",
            JobDescriptionMsg: "Me gusta hacer una renovación completa de la casa, incluida una cocina Me gusta hacer una renovación completa de la casa, incluida una cocina Me gusta hacer una renovación completa de la casa, incluida una uno uno uno uno uno uno uno",
            Attachments: "Archivos adjuntos",
            ACCEPTTOBID: "ACEPTAR OFERTA",
            Congratulationsandgoodluckonyourbidding :"Felicitaciones y buena suerte con su oferta.",
            Createbidlater:"Crear oferta más tarde",
            Setmatchingcriteriasforjobopportunities:"Establecer criterios coincidentes para las oportunidades laborales",
            
        }
    }
];

export type languageProps = {
    id: string;
    name: string;
    code: string;
};

export const appLanguages: languageProps[] = [
    {
        id: '0',
        name: 'English',
        code: 'en'
    },
    {
        id: '1',
        name: 'chinese',
        code: 'ch'
    },
    {
        id: '5',
        name: 'Spanish',
        code: 'es'
    }
];
