export const VALIDATIONMESSAGE = [
    `Please enter email.`,
    `Please enter a valid password.`,
    `Email addresses from example.com are not allowed.`,
    `Invalid email or phone number format.`,
    `Password must be at least 6 characters.`,
    `Please enter a phone number`,
    `Please enter a valid phone number.`,
    `Please enter both passwords`,
    `Passwords do not match.`,
    `Please fill all fields.`,
    `Please enter valid email.`,
    `Please enter code.`,
    `Invalid phone number.`,
    `First Name Is Required`,
    `Zip is invalid`,
    'Primary speciality is not selected',
    'Industry is not selected',
    'Job type is not selected',
]